### ISSUE TITLE
Error: Unable to load Archetype Catalog ...: SAXParseException2

### ISSUE THREAD

**Issue by randycasburn** [dmarks2/maven-archetypes-catalog-plugin#12]
Error: Unable to load Archetype Catalog ...: SAXParseException2

Valid catalog file:

archetype-catalog.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<archetype-catalog  xmlns="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0 http://maven.apache.org/xsd/archetype-catalog-1.0.0.xsd">

    <archetypes>
        <archetype>
            <groupId>org.example</groupId>
            <artifactId>basic</artifactId>
            <version>1.0.0</version>
            <repository>https://validtarget</repository>
            <description>This archetype creates a standard Maven directory structure populated with placeholder files
            </description>
        </archetype>
    </archetypes>
</archetype-catalog>
```

This is valid XML copied and pasted directly from the [documentation](http://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html) 

[Validated here](https://www.freeformatter.com/xml-validator-xsd.html)

**Comment by dmarks2** [comment]
thanks @randycasburn for your bug report.

However I am not able to reproduce the issue. I copied the above to a file and added that archetype-catalog.xml manually to the Maven Archetype Catalogs in IntellIJ IDEA. I was able to create a new project and select the org.example:basic archetype in the archetype list.

No error occured here.

Can you give some more detailled instructions on how the error occurs? Which IntelliJ IDEA version are you using? Which Java version is used to start up IDEA?

**Comment by randycasburn** [comment]
Hi @dominikmarks - I found the error and meant to comeback and close this.  The hosted archetypes are part of a multi-module project and the parent POM had an obscure syntax error I did not see and my IDE did not inform me about. Thanks for taking the time to respond.
