### ISSUE TITLE
URL does not point to a valid archetype-catalog.xml

### ISSUE THREAD

**Issue by qomosoloto** [dmarks2/maven-archetypes-catalog-plugin#2]
Hi,I got an error like title said,the url is "http://repo1.maven.org/maven2/archetype-catalog.xml",anything wrong?

**Comment by dmarks2** [comment]
The Archetype Catalog from the central maven repository does not declare a proper namespace in the XML file. Therefore the IntelliJ Plugin was not able to verify that file.

I fixed the issue by applying the archetype catalog xsd namespace if no namespace is given in an Archetype Catalog.

**Comment by qomosoloto** [comment]
Great,it worked~Thank you.
