### ISSUE TITLE
Marked as incompatible

### ISSUE THREAD

**Issue by quux-aivar** [dmarks2/maven-archetypes-catalog-plugin#20]
Plugin is marked as incompatible on **IntelliJ IDEA 2022.2.2**

**Comment by dmarks2** [comment]
@quux-aivar Thank you for your ticket. Since 2022.2 it is possible to create new Maven projects from archetypes out of the box.

So my plugin is no longer required for 2022.2, therefore I marked it as incompatible.

**Comment by quux-aivar** [comment]
Thank you for info.
