### ISSUE TITLE
URL does not support Authentication

### ISSUE THREAD

**Issue by kenime** [dmarks2/maven-archetypes-catalog-plugin#5]
I would suggest to support Archetype URL Authentication by detecting if there is authentication info provided in URL, i.e. "http://[username]:[password]@[url]"

**Comment by dmarks2** [comment]
It is possible to add authenticated URLs for reading the Archetype Catalogs. However this would not solve the problem when actually generating new Maven projects from an archetype.

The authentication has to be defined in your settings.xml according (see [Maven FAQ](http://maven.apache.org/archetype/maven-archetype-plugin/faq.html#authentication)).

**Comment by dmarks2** [comment]
Implemented in Version 1.2.2
