### ISSUE TITLE
 plugin is not using requiredProperty

### ISSUE THREAD

**Issue by igivon** [dmarks2/maven-archetypes-catalog-plugin#7]
when creating new project the plugin is not using requiredProperty set at archetype-metadata.xml, for example: 
<requiredProperty key="version">
            <defaultValue>1.0-SNAPSHOT</defaultValue>
</requiredProperty>

**Comment by dmarks2** [comment]
Can you  provide some more details about the problem? Can you give an example that does not work as you expect?

Probably is this problem related to this bug in the official IntelliJ Issue tracker? https://youtrack.jetbrains.com/issue/IDEA-81665

**Comment by igivon** [comment]
It Seems to me you are right and its the same issue.
im using the requiredProperty to enter default values both to groupId and version. for the artifactId im using it to verify regex match ( so it will always be the same structure ).
When using archetype-maven plugin:generate the plugin is doing great job, skipping the default values and verify the regex - - i Expect Intellij to do the same

**Comment by dmarks2** [comment]
The problem has to be fixed by Jetbrains. There is nothing I can do about it within my IDEA plugin.
