### ISSUE TITLE
Maven Archetypes Catalog Plugin 1.2.5 and Java 9

### ISSUE THREAD

**Issue by wirepatch** [dmarks2/maven-archetypes-catalog-plugin#8]
I upgraded to current Oracle  9.0.4+11 jdk+jre using most recent idea ultimate 2017.3.5  »without JDK« version. The `maven-archetypes-catalog-plugin` no longer works. I've attached `~/.IntelliJIdea2017.3/system/log/idea.log` wrapped as
[idea.zip](https://github.com/dmarks2/maven-archetypes-catalog-plugin/files/1810191/idea.zip).

This logfile results from restarting idea after installing the plugin. The first exception happens just on idea startup (don't even know if related to the problem in question). The second one occurs when trying to configure the plugin using »Configure« --> »Settings« --> »Build,Execution,Deployment«: The usual »Maven Archetype Catalogs« option does not show up.

**Comment by wirepatch** [comment]
Problem due to own Error using a Java 9 Runtime for IntelliJ itself rather then the bundled OpenJDK 8 runtime.

**Comment by dmarks2** [comment]
I can confirm this to be a bug when using Java 9 runtime for IntelliJ IDEA.

**Comment by dmarks2** [comment]
Issue has been fixed and submitted to plugins.jetbrains.com.
