### ISSUE TITLE
has installed plugin and restart IDEA，but there is no plus sign in the upper right corner of the window

### ISSUE THREAD

**Issue by caoyaochong** [dmarks2/maven-archetypes-catalog-plugin#9]
hello，
I have installed the plugin then restart the IDEA，
but there is no plus sign in the upper right corner of the window

![image](https://user-images.githubusercontent.com/7949891/44616992-8761f880-a88d-11e8-8788-f0d9a6f185a5.png)

here is my environment：

IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
Licensed to XXXX
Subscription is active until XXX
For educational use only.
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

 the version of the  plugin installed  is  maven-archetypes-catalog-plugin-1.2.6

**Comment by dmarks2** [comment]
Hello @caoyaochong ,
thank you for your report.

On Macs the Toolbar is shown below the table. So you can find the Add button at the bottom of the table and not at the right side when you are using a Mac. 

Nevertheless I will try to optimize the user interface. E.g. the toolbar disappears if you have a very small screen or you resize the dialog too much.

**Comment by dmarks2** [comment]
User Interface has been optimized in Version 1.3.0
